<?php


/**
 * hook_form_alter()
 * @param  [type] &$form       [description]
 * @param  [type] &$form_state [description]
 * @param  [type] $form_id     [description]
 * @return [type]              [description]
 */

function tfs_common_form_alter(&$form, &$form_state, $form_id) {
  if (commerce_form_callback($form_id, $form_state) == "commerce_cart_add_to_cart_form") {
    $form['submit']['#attributes']['class'][] = "add-to-cart";
   // dsm($form['submit']['#attributes']['class']);
    $form['submit']['#icon']= NULL;
  }
}

function tfs_common_init() {
  //dsm("test");
}

function tfs_common_preprocess_commerce_popup_cart_cart(&$variables) {
// @todo add validations
// commerce_currency_format(123, 'INR');
  $variables['product_total'] = number_format($variables['variables']['order']->commerce_order_total[LANGUAGE_NONE][0]['amount'], 2);
 // dsm($variables);
}


function tfs_common_process_commerce_cart_block(&$vars) {

 // $vars = number_format_$vars['order']->commerce_order_total[LANGUAGE_NONE][0]['amount']
}
